//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_cwiczenie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roslina
    {
        public decimal id_rosliny { get; set; }
        public string nazwa_polska { get; set; }
        public string nazwa_lacinska { get; set; }
        public string rodzina { get; set; }
    }
}
